services:
  # Back End
  backend:
    build: 
      context: ./backend
    ports:
      - 8080:8080
    
  # Front End
  frontend:
    build:
      context: ./frontend
    ports:
      - 4200:4200

  # Database
  database:
    image: postgres:16-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: aspbtemplate